version: '3.5'

volumes:
  pg_project:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=collabr
    volumes:
      - pg_project:/var/lib/postgresql/data
      - ./server/migrations:/var/migrations
    ports:
      - "5432:5432"
    networks:
      - net

networks:
  net:
    driver: bridge