version: '3.5'

volumes:
  pg_project:
  mongodb_data_container:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=collabr
    volumes:
      - pg_project:/var/lib/postgresql/data
      - ./server/migrations:/var/migrations
    ports:
      - "5432:5432"
    networks:
      - net
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

networks:
  net:
    driver: bridge